-- ============================================================================
-- AURA İntegra — KURULUM SIRASI (Supabase SQL Editor)
-- Proje: dipyrdidkvljojkyaqmd (İNTEGRA)
-- ============================================================================
--
-- 1) supabase_migration.sql        — Ana şema (25+ tablo, RLS, fonksiyonlar)
-- 2) supabase_packages_v2.sql      — 3 katmanlı paket sistemi (450/750/1200 ₺)
-- 3) supabase/migrations/20260613_tenant_branding.sql  — Marka alanları (varsa)
-- 4) supabase/migrations/20260614_aura_integra_complete.sql — ERP genişletme
-- 5) supabase/migrations/20260615_platform_admin_features.sql — Platform ayarları, audit log
-- 6) supabase/migrations/20260616_eod_foreign_devices.sql — Gün sonu snapshot, foreign_devices RLS
-- 7) supabase/migrations/20260617_basvuru_monthly_text.sql — Başvuru aylık servis alanı TEXT
-- 8) supabase/migrations/20260618_security_audit.sql — PII şifreleme, API key hash
-- 9) supabase/migrations/20260619_fix_rls_recursion.sql — RLS recursion düzeltmesi
-- 10) supabase/migrations/20260620_ensure_tenant_branding.sql — portal_slug, shop_address
-- 11) supabase/migrations/20260621_documentation_seed.sql — Dokümantasyon seed
--
-- Sonra .env.local:
--   NEXT_PUBLIC_SUPABASE_URL=https://dipyrdidkvljojkyaqmd.supabase.co
--   NEXT_PUBLIC_SUPABASE_ANON_KEY=...
--   SUPABASE_SERVICE_ROLE_KEY=...
--
-- Test: GET /api/health/supabase?view=1&ping=1
-- ============================================================================

-- Hızlı kontrol — 3 paket var mı?
SELECT name, price, max_users, max_branches FROM subscription_plans ORDER BY price;
