"use client";

import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import Link from "next/link";

export default function Hero() {
  return (
    <div className="relative min-h-screen pt-32 pb-20 overflow-hidden bg-gradient-to-b from-slate-50 to-slate-100 flex items-center">
      {/* Background decoration */}
      <div className="absolute top-0 left-1/2 w-full -translate-x-1/2 overflow-hidden pointer-events-none">
        <div className="absolute -top-[20rem] -left-[10rem] w-[40rem] h-[40rem] rounded-full bg-blue-400/20 blur-3xl opacity-60" />
        <div className="absolute top-[10rem] -right-[10rem] w-[30rem] h-[30rem] rounded-full bg-emerald-400/20 blur-3xl opacity-60" />
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 w-full">
        <div className="text-center max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <span className="inline-block py-1 px-3 rounded-full bg-gradient-to-r from-blue-100 to-emerald-100 text-blue-800 text-sm font-semibold mb-6 border border-blue-200 shadow-sm">
              ✨ Yeni Nesil ERP Çözümü v2.0 Yayında
            </span>
            <h1 className="text-5xl md:text-7xl font-extrabold text-slate-900 tracking-tight mb-8 leading-tight">
              Tüm İşletmenizi <br className="hidden md:block" />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-emerald-500">
                Tek Ekrandan Yönetin
              </span>
            </h1>
            <p className="text-xl text-slate-600 mb-10 max-w-2xl mx-auto leading-relaxed">
              Muhasebe, teknik servis, stok ve müşteri yönetimi artık bulutta ve mobil cihazınızda. Esnaf ve KOBİ'ler için tasarlandı, anında kullanıma hazır.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link
              href="/login"
              className="w-full sm:w-auto px-8 py-4 bg-gradient-to-r from-blue-600 to-blue-700 text-white rounded-full font-semibold text-lg hover:from-blue-700 hover:to-blue-800 transition-all shadow-lg shadow-blue-600/30 flex items-center justify-center gap-2 group"
            >
              Hemen Başla
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link
              href="/login"
              className="w-full sm:w-auto px-8 py-4 bg-white text-slate-700 rounded-full font-semibold text-lg border border-slate-200 hover:border-slate-300 hover:bg-slate-50 transition-all flex items-center justify-center shadow-sm"
            >
              Canlı Demoyu İncele
            </Link>
          </motion.div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.4 }}
            className="mt-12 flex flex-col sm:flex-row items-center justify-center gap-6 text-sm text-slate-500"
          >
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-500" />
              <span>Kredi kartı gerekmez</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-500" />
              <span>7/24 Canlı Destek</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-500" />
              <span>Anında Kurulum</span>
            </div>
          </motion.div>
        </div>

        {/* Dashboard Mockup - Realtime Feeling */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.5 }}
          className="mt-20 relative mx-auto max-w-5xl"
        >
          <div className="rounded-2xl border border-slate-200/60 bg-white/50 backdrop-blur-xl shadow-2xl p-2 sm:p-4">
            <div className="rounded-xl overflow-hidden border border-slate-100 bg-slate-50 aspect-video relative flex items-center justify-center">
              {/* This could be replaced with an actual screenshot/image generated by the image tool */}
              <div className="absolute inset-0 bg-gradient-to-br from-slate-100 to-slate-50 flex flex-col p-6">
                 {/* Fake Dashboard Elements */}
                 <div className="h-12 border-b border-slate-200 mb-6 flex items-center justify-between">
                    <div className="flex gap-2">
                       <div className="w-3 h-3 rounded-full bg-red-400"></div>
                       <div className="w-3 h-3 rounded-full bg-amber-400"></div>
                       <div className="w-3 h-3 rounded-full bg-emerald-400"></div>
                    </div>
                    <div className="w-32 h-6 bg-white rounded-md border border-slate-200"></div>
                 </div>
                 <div className="flex gap-6 h-full">
                    <div className="w-48 h-full bg-white rounded-lg border border-slate-200 hidden md:block"></div>
                    <div className="flex-1 flex flex-col gap-6">
                       <div className="flex gap-4">
                          <div className="flex-1 h-24 bg-white rounded-lg border border-slate-200 p-4 relative overflow-hidden">
                              <div className="absolute top-0 left-0 w-1 h-full bg-blue-500"></div>
                              <div className="w-16 h-4 bg-slate-100 rounded mb-2"></div>
                              <div className="w-24 h-8 bg-slate-200 rounded"></div>
                          </div>
                          <div className="flex-1 h-24 bg-white rounded-lg border border-slate-200 p-4 relative overflow-hidden">
                              <div className="absolute top-0 left-0 w-1 h-full bg-emerald-500"></div>
                              <div className="w-16 h-4 bg-slate-100 rounded mb-2"></div>
                              <div className="w-24 h-8 bg-slate-200 rounded"></div>
                          </div>
                          <div className="flex-1 h-24 bg-white rounded-lg border border-slate-200 p-4 relative overflow-hidden">
                              <div className="absolute top-0 left-0 w-1 h-full bg-amber-500"></div>
                              <div className="w-16 h-4 bg-slate-100 rounded mb-2"></div>
                              <div className="w-24 h-8 bg-slate-200 rounded"></div>
                          </div>
                       </div>
                       <div className="flex-1 bg-white rounded-lg border border-slate-200 p-6 flex items-end gap-4 justify-between">
                           {/* Fake chart bars */}
                           {[40, 70, 45, 90, 65, 80, 50].map((h, i) => (
                             <motion.div 
                               key={i}
                               initial={{ height: 0 }}
                               animate={{ height: `${h}%` }}
                               transition={{ duration: 1, delay: 0.8 + (i * 0.1) }}
                               className="w-full bg-blue-500/20 rounded-t-md relative group"
                             >
                                <div className="absolute bottom-0 w-full bg-blue-500 rounded-t-md transition-all duration-500" style={{ height: '70%' }}></div>
                             </motion.div>
                           ))}
                       </div>
                    </div>
                 </div>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
